### ISSUE TITLE
Plan Of Action - Portfolio Website

### ISSUE THREAD

**Issue by proffapt** [proffapt/proffapt.github.io#1]
#### TODO

- [ ] Create a sexy landing page.
- [ ] Complete blogs
  - [ ] C/C++ 
    - [ ] Remove proffapt.github.io on top of the blogs.
  - [ ] EOL
    - [ ] Refactor the blog text
    - [ ] Create the blog publishing ready
  - [ ] Create a good section for blogs.
- [x] Add SSL cert.
- [ ] Unblock on campus network.

**Comment by proffapt** [comment]
No need to be heere
